[window]
dimensions = { columns = 105, lines = 30 }
padding = { x = 1, y = 0 }

# Does not work on Wayland
#position = { x = 35, y = 35 }

# Does not work on X11 (nor Mutter)
#opacity = 0.60
#blur = true

[font]
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }
